[build]
  command = "npm run build && mkdir -p netlify/edge-functions && cp -r dist/server/. netlify/edge-functions/"
  publish = "dist/client"

[[edge_functions]]
  path = "/*"
  function = "server"
