/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAlumniIndexRouteImport } from './routes/_app.alumni.index'
import { Route as AppAlumniNewRouteImport } from './routes/_app.alumni.new'
import { Route as AppAlumniIdRouteImport } from './routes/_app.alumni.$id'
import { Route as AppAlumniIdEditRouteImport } from './routes/_app.alumni.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumniIndexRoute = AppAlumniIndexRouteImport.update({
  id: '/alumni/',
  path: '/alumni/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumniNewRoute = AppAlumniNewRouteImport.update({
  id: '/alumni/new',
  path: '/alumni/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumniIdRoute = AppAlumniIdRouteImport.update({
  id: '/alumni/$id',
  path: '/alumni/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumniIdEditRoute = AppAlumniIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppAlumniIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/alumni/$id': typeof AppAlumniIdRouteWithChildren
  '/alumni/new': typeof AppAlumniNewRoute
  '/alumni/': typeof AppAlumniIndexRoute
  '/alumni/$id/edit': typeof AppAlumniIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/alumni/$id': typeof AppAlumniIdRouteWithChildren
  '/alumni/new': typeof AppAlumniNewRoute
  '/alumni': typeof AppAlumniIndexRoute
  '/alumni/$id/edit': typeof AppAlumniIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/alumni/$id': typeof AppAlumniIdRouteWithChildren
  '/_app/alumni/new': typeof AppAlumniNewRoute
  '/_app/alumni/': typeof AppAlumniIndexRoute
  '/_app/alumni/$id/edit': typeof AppAlumniIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/alumni/$id'
    | '/alumni/new'
    | '/alumni/'
    | '/alumni/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/alumni/$id'
    | '/alumni/new'
    | '/alumni'
    | '/alumni/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/alumni/$id'
    | '/_app/alumni/new'
    | '/_app/alumni/'
    | '/_app/alumni/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumni/': {
      id: '/_app/alumni/'
      path: '/alumni'
      fullPath: '/alumni/'
      preLoaderRoute: typeof AppAlumniIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumni/new': {
      id: '/_app/alumni/new'
      path: '/alumni/new'
      fullPath: '/alumni/new'
      preLoaderRoute: typeof AppAlumniNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumni/$id': {
      id: '/_app/alumni/$id'
      path: '/alumni/$id'
      fullPath: '/alumni/$id'
      preLoaderRoute: typeof AppAlumniIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumni/$id/edit': {
      id: '/_app/alumni/$id/edit'
      path: '/edit'
      fullPath: '/alumni/$id/edit'
      preLoaderRoute: typeof AppAlumniIdEditRouteImport
      parentRoute: typeof AppAlumniIdRoute
    }
  }
}

interface AppAlumniIdRouteChildren {
  AppAlumniIdEditRoute: typeof AppAlumniIdEditRoute
}

const AppAlumniIdRouteChildren: AppAlumniIdRouteChildren = {
  AppAlumniIdEditRoute: AppAlumniIdEditRoute,
}

const AppAlumniIdRouteWithChildren = AppAlumniIdRoute._addFileChildren(
  AppAlumniIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAlumniIdRoute: typeof AppAlumniIdRouteWithChildren
  AppAlumniNewRoute: typeof AppAlumniNewRoute
  AppAlumniIndexRoute: typeof AppAlumniIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAlumniIdRoute: AppAlumniIdRouteWithChildren,
  AppAlumniNewRoute: AppAlumniNewRoute,
  AppAlumniIndexRoute: AppAlumniIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
