/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMentorshipRouteImport } from './routes/_app.mentorship'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppSurveysIndexRouteImport } from './routes/_app.surveys.index'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as AppAlumniIndexRouteImport } from './routes/_app.alumni.index'
import { Route as SurveyRespondTokenRouteImport } from './routes/survey.respond.$token'
import { Route as AppSurveysNewRouteImport } from './routes/_app.surveys.new'
import { Route as AppSurveysIdRouteImport } from './routes/_app.surveys.$id'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsHelpContentRouteImport } from './routes/_app.settings.help-content'
import { Route as AppSettingsAuditLogRouteImport } from './routes/_app.settings.audit-log'
import { Route as AppCampaignsNewRouteImport } from './routes/_app.campaigns.new'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'
import { Route as AppAlumniNewRouteImport } from './routes/_app.alumni.new'
import { Route as AppAlumniIdRouteImport } from './routes/_app.alumni.$id'
import { Route as AppSurveysIdEditRouteImport } from './routes/_app.surveys.$id_.edit'
import { Route as AppSettingsUsersNewRouteImport } from './routes/_app.settings.users_.new'
import { Route as AppCampaignsIdEditRouteImport } from './routes/_app.campaigns.$id_.edit'
import { Route as AppAlumniIdEditRouteImport } from './routes/_app.alumni.$id_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMentorshipRoute = AppMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysIndexRoute = AppSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumniIndexRoute = AppAlumniIndexRouteImport.update({
  id: '/alumni/',
  path: '/alumni/',
  getParentRoute: () => AppRoute,
} as any)
const SurveyRespondTokenRoute = SurveyRespondTokenRouteImport.update({
  id: '/survey/respond/$token',
  path: '/survey/respond/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSurveysNewRoute = AppSurveysNewRouteImport.update({
  id: '/surveys/new',
  path: '/surveys/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysIdRoute = AppSurveysIdRouteImport.update({
  id: '/surveys/$id',
  path: '/surveys/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsHelpContentRoute = AppSettingsHelpContentRouteImport.update({
  id: '/settings/help-content',
  path: '/settings/help-content',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditLogRoute = AppSettingsAuditLogRouteImport.update({
  id: '/settings/audit-log',
  path: '/settings/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumniNewRoute = AppAlumniNewRouteImport.update({
  id: '/alumni/new',
  path: '/alumni/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumniIdRoute = AppAlumniIdRouteImport.update({
  id: '/alumni/$id',
  path: '/alumni/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysIdEditRoute = AppSurveysIdEditRouteImport.update({
  id: '/surveys/$id_/edit',
  path: '/surveys/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersNewRoute = AppSettingsUsersNewRouteImport.update({
  id: '/settings/users_/new',
  path: '/settings/users/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdEditRoute = AppCampaignsIdEditRouteImport.update({
  id: '/campaigns/$id_/edit',
  path: '/campaigns/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumniIdEditRoute = AppAlumniIdEditRouteImport.update({
  id: '/alumni/$id_/edit',
  path: '/alumni/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/mentorship': typeof AppMentorshipRoute
  '/alumni/$id': typeof AppAlumniIdRoute
  '/alumni/new': typeof AppAlumniNewRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/help-content': typeof AppSettingsHelpContentRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/surveys/$id': typeof AppSurveysIdRoute
  '/surveys/new': typeof AppSurveysNewRoute
  '/survey/respond/$token': typeof SurveyRespondTokenRoute
  '/alumni/': typeof AppAlumniIndexRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
  '/surveys/': typeof AppSurveysIndexRoute
  '/alumni/$id/edit': typeof AppAlumniIdEditRoute
  '/campaigns/$id/edit': typeof AppCampaignsIdEditRoute
  '/settings/users/new': typeof AppSettingsUsersNewRoute
  '/surveys/$id/edit': typeof AppSurveysIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/mentorship': typeof AppMentorshipRoute
  '/alumni/$id': typeof AppAlumniIdRoute
  '/alumni/new': typeof AppAlumniNewRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/settings/help-content': typeof AppSettingsHelpContentRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/surveys/$id': typeof AppSurveysIdRoute
  '/surveys/new': typeof AppSurveysNewRoute
  '/survey/respond/$token': typeof SurveyRespondTokenRoute
  '/alumni': typeof AppAlumniIndexRoute
  '/campaigns': typeof AppCampaignsIndexRoute
  '/surveys': typeof AppSurveysIndexRoute
  '/alumni/$id/edit': typeof AppAlumniIdEditRoute
  '/campaigns/$id/edit': typeof AppCampaignsIdEditRoute
  '/settings/users/new': typeof AppSettingsUsersNewRoute
  '/surveys/$id/edit': typeof AppSurveysIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/mentorship': typeof AppMentorshipRoute
  '/_app/alumni/$id': typeof AppAlumniIdRoute
  '/_app/alumni/new': typeof AppAlumniNewRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/_app/settings/audit-log': typeof AppSettingsAuditLogRoute
  '/_app/settings/help-content': typeof AppSettingsHelpContentRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/surveys/$id': typeof AppSurveysIdRoute
  '/_app/surveys/new': typeof AppSurveysNewRoute
  '/survey/respond/$token': typeof SurveyRespondTokenRoute
  '/_app/alumni/': typeof AppAlumniIndexRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
  '/_app/surveys/': typeof AppSurveysIndexRoute
  '/_app/alumni/$id_/edit': typeof AppAlumniIdEditRoute
  '/_app/campaigns/$id_/edit': typeof AppCampaignsIdEditRoute
  '/_app/settings/users_/new': typeof AppSettingsUsersNewRoute
  '/_app/surveys/$id_/edit': typeof AppSurveysIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/mentorship'
    | '/alumni/$id'
    | '/alumni/new'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/settings/audit-log'
    | '/settings/help-content'
    | '/settings/users'
    | '/surveys/$id'
    | '/surveys/new'
    | '/survey/respond/$token'
    | '/alumni/'
    | '/campaigns/'
    | '/surveys/'
    | '/alumni/$id/edit'
    | '/campaigns/$id/edit'
    | '/settings/users/new'
    | '/surveys/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/mentorship'
    | '/alumni/$id'
    | '/alumni/new'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/settings/audit-log'
    | '/settings/help-content'
    | '/settings/users'
    | '/surveys/$id'
    | '/surveys/new'
    | '/survey/respond/$token'
    | '/alumni'
    | '/campaigns'
    | '/surveys'
    | '/alumni/$id/edit'
    | '/campaigns/$id/edit'
    | '/settings/users/new'
    | '/surveys/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/mentorship'
    | '/_app/alumni/$id'
    | '/_app/alumni/new'
    | '/_app/campaigns/$id'
    | '/_app/campaigns/new'
    | '/_app/settings/audit-log'
    | '/_app/settings/help-content'
    | '/_app/settings/users'
    | '/_app/surveys/$id'
    | '/_app/surveys/new'
    | '/survey/respond/$token'
    | '/_app/alumni/'
    | '/_app/campaigns/'
    | '/_app/surveys/'
    | '/_app/alumni/$id_/edit'
    | '/_app/campaigns/$id_/edit'
    | '/_app/settings/users_/new'
    | '/_app/surveys/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SurveyRespondTokenRoute: typeof SurveyRespondTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/mentorship': {
      id: '/_app/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof AppMentorshipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/': {
      id: '/_app/surveys/'
      path: '/surveys'
      fullPath: '/surveys/'
      preLoaderRoute: typeof AppSurveysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumni/': {
      id: '/_app/alumni/'
      path: '/alumni'
      fullPath: '/alumni/'
      preLoaderRoute: typeof AppAlumniIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/survey/respond/$token': {
      id: '/survey/respond/$token'
      path: '/survey/respond/$token'
      fullPath: '/survey/respond/$token'
      preLoaderRoute: typeof SurveyRespondTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/surveys/new': {
      id: '/_app/surveys/new'
      path: '/surveys/new'
      fullPath: '/surveys/new'
      preLoaderRoute: typeof AppSurveysNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/$id': {
      id: '/_app/surveys/$id'
      path: '/surveys/$id'
      fullPath: '/surveys/$id'
      preLoaderRoute: typeof AppSurveysIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/help-content': {
      id: '/_app/settings/help-content'
      path: '/settings/help-content'
      fullPath: '/settings/help-content'
      preLoaderRoute: typeof AppSettingsHelpContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit-log': {
      id: '/_app/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof AppSettingsAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumni/new': {
      id: '/_app/alumni/new'
      path: '/alumni/new'
      fullPath: '/alumni/new'
      preLoaderRoute: typeof AppAlumniNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumni/$id': {
      id: '/_app/alumni/$id'
      path: '/alumni/$id'
      fullPath: '/alumni/$id'
      preLoaderRoute: typeof AppAlumniIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surveys/$id_/edit': {
      id: '/_app/surveys/$id_/edit'
      path: '/surveys/$id/edit'
      fullPath: '/surveys/$id/edit'
      preLoaderRoute: typeof AppSurveysIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users_/new': {
      id: '/_app/settings/users_/new'
      path: '/settings/users/new'
      fullPath: '/settings/users/new'
      preLoaderRoute: typeof AppSettingsUsersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id_/edit': {
      id: '/_app/campaigns/$id_/edit'
      path: '/campaigns/$id/edit'
      fullPath: '/campaigns/$id/edit'
      preLoaderRoute: typeof AppCampaignsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alumni/$id_/edit': {
      id: '/_app/alumni/$id_/edit'
      path: '/alumni/$id/edit'
      fullPath: '/alumni/$id/edit'
      preLoaderRoute: typeof AppAlumniIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppMentorshipRoute: typeof AppMentorshipRoute
  AppAlumniIdRoute: typeof AppAlumniIdRoute
  AppAlumniNewRoute: typeof AppAlumniNewRoute
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppSettingsAuditLogRoute: typeof AppSettingsAuditLogRoute
  AppSettingsHelpContentRoute: typeof AppSettingsHelpContentRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSurveysIdRoute: typeof AppSurveysIdRoute
  AppSurveysNewRoute: typeof AppSurveysNewRoute
  AppAlumniIndexRoute: typeof AppAlumniIndexRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
  AppSurveysIndexRoute: typeof AppSurveysIndexRoute
  AppAlumniIdEditRoute: typeof AppAlumniIdEditRoute
  AppCampaignsIdEditRoute: typeof AppCampaignsIdEditRoute
  AppSettingsUsersNewRoute: typeof AppSettingsUsersNewRoute
  AppSurveysIdEditRoute: typeof AppSurveysIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppMentorshipRoute: AppMentorshipRoute,
  AppAlumniIdRoute: AppAlumniIdRoute,
  AppAlumniNewRoute: AppAlumniNewRoute,
  AppCampaignsIdRoute: AppCampaignsIdRoute,
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppSettingsAuditLogRoute: AppSettingsAuditLogRoute,
  AppSettingsHelpContentRoute: AppSettingsHelpContentRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSurveysIdRoute: AppSurveysIdRoute,
  AppSurveysNewRoute: AppSurveysNewRoute,
  AppAlumniIndexRoute: AppAlumniIndexRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
  AppSurveysIndexRoute: AppSurveysIndexRoute,
  AppAlumniIdEditRoute: AppAlumniIdEditRoute,
  AppCampaignsIdEditRoute: AppCampaignsIdEditRoute,
  AppSettingsUsersNewRoute: AppSettingsUsersNewRoute,
  AppSurveysIdEditRoute: AppSurveysIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SurveyRespondTokenRoute: SurveyRespondTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
